### ISSUE TITLE
Due date holdover from Fall 2019?

### ISSUE THREAD

**Issue by kevingreenman** [mitmath/18337#14]
There's a line in the Final Project section that says "Final project topics must be declared by October 18th with a 1 page extended abstract.". I looked at the commit history and it looks like this was here in Fall 2019, and it conflicts with the October 30th due date for the project proposal given earlier in the README.

**Comment by kevingreenman** [comment]
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Yes the 30th is the correct one.
